# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, digestiveFunctors, HandsomeSoup, hspec, hspecCore
, hxt, lens, mtl, snap, snapCore, text, transformers
}:

cabal.mkDerivation (self: {
  pname = "hspec-snap";
  version = "0.3.2.2";
  sha256 = "0w2zvzpa5294y8hbjjnpd9kyq42i8l5ca6dpf2zl8mwnmfqzc733";
  jailbreak = true;
  buildDepends = [
    digestiveFunctors HandsomeSoup hspec hspecCore hxt lens mtl snap
    snapCore text transformers
  ];
  doCheck = false;
  meta = {
    homepage = "https://github.com/dbp/hspec-snap";
    description = "A library for testing with Hspec and the Snap Web Framework";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
