# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ haskellPackages ? (import <nixpkgs> {}).haskellPackages }:

with haskellPackages; cabal.mkDerivation (self: {
  pname = "cataskell";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    aeson engineIo engineIoSnap fgl httpTypes lens MonadRandom mtl
    random randomShuffle snapCore snapServer socketIo stm text
    transformers wai
  ];
  buildTools = [ cabalInstall_1_20_0_6 ];
  hspecSnap = callPackage ./hspec-snap.nix {};
  testDepends = [
    aeson deepseq fgl fglVisualize hspec self.hspecSnap lens MonadRandom mtl
    QuickCheck random randomShuffle wai
  ];
  shellHook =
    ''
      e() { ~/.nix-profile/Applications/Emacs.app/Contents/MacOS/emacs $@ & }
    '';
  meta = {
    homepage = "http://github.com/chrisjr/cataskell";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
