# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ haskellPackages ? (import <nixpkgs> {}).haskellPackages }:

with haskellPackages; cabal.mkDerivation (self: {
  pname = "cataskell";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    aeson engineIo engineIoYesod fgl httpTypes lens MonadRandom mtl
    random randomShuffle socketIo wai warp yesodCore
  ];
  testDepends = [
    aeson deepseq fgl fglVisualize hspec hspecWai hspecWaiJson lens
    MonadRandom mtl QuickCheck random randomShuffle
  ];
  buildTools = [ cabalInstall_1_20_0_6 yesodBin ];
  shellHook =
    ''
      e() { ~/.nix-profile/Applications/Emacs.app/Contents/MacOS/Emacs $@ & }
    '';
  meta = {
    homepage = "http://github.com/chrisjr/cataskell";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
